In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [3]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6021, 0.5278],
        [0.5827, 0.8409]]) 



In [4]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1734, 0.0415, 0.2683],
        [0.7990, 0.7305, 0.4815]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


tensor([[0.7833, 0.2564, 0.4119, 0.9183, 0.7833, 0.2564, 0.4119, 0.9183, 0.7833,
         0.2564, 0.4119, 0.9183],
        [0.3090, 0.4903, 0.0989, 0.2991, 0.3090, 0.4903, 0.0989, 0.2991, 0.3090,
         0.4903, 0.0989, 0.2991],
        [0.6162, 0.7459, 0.8472, 0.7588, 0.6162, 0.7459, 0.8472, 0.7588, 0.6162,
         0.7459, 0.8472, 0.7588]])


In [7]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.6136, 0.0657, 0.1697, 0.8432],
        [0.0955, 0.2404, 0.0098, 0.0895],
        [0.3797, 0.5563, 0.7178, 0.5758]])